spring:
  datasource:
    url: jdbc:mysql://116.196.123.49:3306/foodtalk?useSSL=false
    username: user
    password: wr000000
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080

loginVerify: false
key: foodtalk
comment_img_path: /res/commentImg/
food_img_path: /res/foodImg/
comment_img_url: http://116.196.123.49:7777/commentImg/
food_img_url: http://116.196.123.49:7777/foodImg/
checkURL: http://139.199.66.15:5000/api/track





